# Generated by Django 6.0.5 on 2026-06-02 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=20)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
            ],
            options={
                'verbose_name': 'Business Profile',
            },
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='client',
        ),
        migrations.AddField(
            model_name='invoice',
            name='client_address',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='invoice',
            name='client_email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='invoice',
            name='client_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='invoice',
            name='client_phone',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.DeleteModel(
            name='Client',
        ),
    ]
